name: Build WPF

on:
  push:
    branches: [main]
    paths:
      - "WPF/**"
      - ".github/workflows/build-wpf.yml"
  pull_request:
    branches: [main]
    paths:
      - "WPF/**"
      - ".github/workflows/build-wpf.yml"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet publish WPF/FluxDB/FluxDB.csproj -c Release -o "${{ github.workspace }}\bin\"